services:
  backend:
    build: ./backend
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase_data:/app/pb_data
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3110:80"
    depends_on:
      - backend
    restart: unless-stopped

#volumes:
#  pocketbase_data: