/**
 * Odyssey demo location seed data.
 */

import type { LocationRow } from '../../types/schema';
import { LOCATION_IDS, SEED_CAMPAIGN_ID, SEED_CONTINUITY_ID, TAG_IDS } from '../types';

const SEED_TIMESTAMP = '2024-01-01T00:00:00.000Z';

const campaignIds = JSON.stringify([SEED_CAMPAIGN_ID]);

export const seedLocations: LocationRow[] = [
  // === PLANES ===
  {
    id: LOCATION_IDS.mortalRealm,
    name: 'Mortal Realm',
    type: 'Plane',
    description:
      'The world of mortals, where gods meddle in human affairs and heroes carve their legends into history.',
    status: 'complete',
    parentId: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: '[]',
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: LOCATION_IDS.divineRealm,
    name: 'Divine Realm',
    type: 'Plane',
    description:
      'The realm of the gods, where immortals watch over mortals and occasionally intervene in their fates.',
    status: 'complete',
    parentId: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: JSON.stringify([TAG_IDS.divine]),
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },

  // === TERRITORIES (under Mortal Realm) ===
  {
    id: LOCATION_IDS.aegeanSea,
    name: 'The Aegean Sea',
    type: 'Territory',
    description:
      'The wine-dark sea, home to countless islands and the treacherous waters Odysseus must navigate to return home.',
    status: 'complete',
    parentId: LOCATION_IDS.mortalRealm,
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: '[]',
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },

  // === LOCALES (under Aegean Sea) ===
  {
    id: LOCATION_IDS.ithaca,
    name: 'Ithaca',
    type: 'Locale',
    description:
      'The rocky island kingdom of Odysseus. His faithful wife Penelope waits here, beset by suitors who believe him dead. Home. The goal.',
    status: 'complete',
    parentId: LOCATION_IDS.aegeanSea,
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: JSON.stringify([TAG_IDS.home, TAG_IDS.endgame]),
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: LOCATION_IDS.troy,
    name: 'Troy',
    type: 'Locale',
    description:
      'The fallen city. After ten years of war, Troy lies in ruins. The Greeks have won, but the journey home will prove just as perilous as the war itself.',
    status: 'complete',
    parentId: LOCATION_IDS.aegeanSea,
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: '[]',
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: LOCATION_IDS.cyclopsIsland,
    name: 'Cyclops Island',
    type: 'Locale',
    description:
      'A wild island inhabited by the Cyclopes—giant one-eyed shepherds who know nothing of laws, ships, or the sacred bonds of hospitality. Polyphemus dwells here in his cave.',
    status: 'complete',
    parentId: LOCATION_IDS.aegeanSea,
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: JSON.stringify([TAG_IDS.hostile]),
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: LOCATION_IDS.sirensStrait,
    name: "Sirens' Strait",
    type: 'Locale',
    description:
      'A narrow passage flanked by jagged rocks where the Sirens sing. Their voices are irresistible—sailors who hear them steer toward the sound and wreck upon the shore.',
    status: 'complete',
    parentId: LOCATION_IDS.aegeanSea,
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: JSON.stringify([TAG_IDS.magic, TAG_IDS.hostile]),
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },

  // === LOCALES (under Mortal Realm, not Aegean) ===
  {
    id: LOCATION_IDS.aeolia,
    name: 'Aeolia',
    type: 'Locale',
    description:
      'The floating island of Aeolus, keeper of the winds. Bronze walls surround this impossible place where the wind god lives with his twelve children.',
    status: 'complete',
    parentId: LOCATION_IDS.mortalRealm,
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: JSON.stringify([TAG_IDS.divine, TAG_IDS.ally]),
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: LOCATION_IDS.aeaea,
    name: 'Aeaea',
    type: 'Locale',
    description:
      "Circe's island, shrouded in mist. Wild wolves and lions roam the forests, tame as dogs—former men transformed by the witch's magic. Her palace lies at the island's heart.",
    status: 'complete',
    parentId: LOCATION_IDS.mortalRealm,
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: JSON.stringify([TAG_IDS.magic]),
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: LOCATION_IDS.ogygia,
    name: 'Ogygia',
    type: 'Locale',
    description:
      "Calypso's hidden island, a paradise at the edge of the world. The nymph keeps Odysseus here for seven years, offering immortality if he will stay forever.",
    status: 'complete',
    parentId: LOCATION_IDS.mortalRealm,
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: JSON.stringify([TAG_IDS.divine]),
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },

  // === LOCALES (under Divine Realm) ===
  {
    id: LOCATION_IDS.mountOlympus,
    name: 'Mount Olympus',
    type: 'Locale',
    description:
      'The seat of the gods, rising above the clouds. Here Zeus holds court and the Olympians debate the fates of mortals. Athena advocates for Odysseus from these halls.',
    status: 'complete',
    parentId: LOCATION_IDS.divineRealm,
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: JSON.stringify([TAG_IDS.divine]),
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: LOCATION_IDS.underworld,
    name: 'The Underworld',
    type: 'Locale',
    description:
      'The realm of the dead, ruled by Hades. Odysseus must journey here to consult the blind prophet Tiresias. The shades of the dead gather at the blood-offering, desperate to speak.',
    status: 'complete',
    parentId: LOCATION_IDS.divineRealm,
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    tagIds: JSON.stringify([TAG_IDS.divine, TAG_IDS.oracle]),
    map: '',
    images: '[]',
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
];
