/**
 * Odyssey demo NPC seed data.
 */

import type { NpcRow } from '../../types/schema';
import {
  LOCATION_IDS,
  NPC_IDS,
  SEED_CAMPAIGN_ID,
  SEED_CONTINUITY_ID,
  TAG_IDS,
} from '../types';

const SEED_TIMESTAMP = '2024-01-01T00:00:00.000Z';

const campaignIds = JSON.stringify([SEED_CAMPAIGN_ID]);

export const seedNpcs: NpcRow[] = [
  // === PROTAGONISTS ===
  {
    id: NPC_IDS.odysseus,
    name: 'Odysseus',
    race: 'Human',
    role: 'King of Ithaca',
    background:
      'The cunning hero of Troy, architect of the wooden horse. Now he seeks only to return home to his wife and son. But the gods have other plans, and his own cleverness often makes things worse.',
    status: 'complete',
    image: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    locationIds: JSON.stringify([LOCATION_IDS.ithaca]),
    noteIds: '[]',
    tagIds: JSON.stringify([TAG_IDS.ally]),
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: NPC_IDS.eurylochus,
    name: 'Eurylochus',
    race: 'Human',
    role: 'Second-in-Command',
    background:
      "Odysseus's brother-in-law and most trusted lieutenant. Cautious where Odysseus is bold, he often counsels retreat—sometimes wisely, sometimes not. The crew listens to him when the captain's judgment seems reckless.",
    status: 'complete',
    image: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    locationIds: '[]',
    noteIds: '[]',
    tagIds: JSON.stringify([TAG_IDS.ally]),
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: NPC_IDS.penelope,
    name: 'Penelope',
    race: 'Human',
    role: 'Queen of Ithaca',
    background:
      'Faithful wife of Odysseus, waiting twenty years for his return. She holds off the suitors with her own cunning—weaving a shroud by day, unraveling it by night. As clever as her husband, in her own way.',
    status: 'complete',
    image: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    locationIds: JSON.stringify([LOCATION_IDS.ithaca]),
    noteIds: '[]',
    tagIds: JSON.stringify([TAG_IDS.ally, TAG_IDS.home]),
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },

  // === ANTAGONISTS / OBSTACLES ===
  {
    id: NPC_IDS.polyphemus,
    name: 'Polyphemus',
    race: 'Cyclops',
    role: 'Son of Poseidon',
    background:
      "A one-eyed giant who tends sheep on his island. He has no regard for the laws of hospitality—or for the lives of sailors who stumble into his cave. Now blinded by Odysseus's cunning, he has called down his father's curse.",
    status: 'complete',
    image: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    locationIds: JSON.stringify([LOCATION_IDS.cyclopsIsland]),
    noteIds: '[]',
    tagIds: JSON.stringify([TAG_IDS.hostile, TAG_IDS.blinded, TAG_IDS.divine]),
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: NPC_IDS.poseidon,
    name: 'Poseidon',
    race: 'God',
    role: 'God of the Sea',
    background:
      "Earth-Shaker, lord of the wine-dark sea. Father of Polyphemus. Since Odysseus blinded his son, Poseidon has sworn that the hero will never reach home easily. Every storm, every shipwreck, every delay—the sea god's wrath.",
    status: 'complete',
    image: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    locationIds: JSON.stringify([LOCATION_IDS.divineRealm]),
    noteIds: '[]',
    tagIds: JSON.stringify([TAG_IDS.divine, TAG_IDS.hostile, TAG_IDS.grudge]),
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },

  // === AMBIGUOUS / COMPLEX ===
  {
    id: NPC_IDS.circe,
    name: 'Circe',
    race: 'Nymph',
    role: 'Witch of Aeaea',
    background:
      'A powerful sorceress who transforms men into swine. She first enchants half of Odysseus\'s crew, but when he resists her magic (with Hermes\'s help), she becomes an ally and lover. She guides him to the Underworld.',
    status: 'complete',
    image: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    locationIds: JSON.stringify([LOCATION_IDS.aeaea]),
    noteIds: '[]',
    tagIds: JSON.stringify([TAG_IDS.magic, TAG_IDS.ally]),
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: NPC_IDS.calypso,
    name: 'Calypso',
    race: 'Nymph',
    role: 'Goddess of Ogygia',
    background:
      'A beautiful nymph who keeps Odysseus on her island for seven years, offering him immortality if he will stay as her husband. She loves him truly, but he yearns for home. When Zeus commands it, she reluctantly lets him go.',
    status: 'complete',
    image: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    locationIds: JSON.stringify([LOCATION_IDS.ogygia]),
    noteIds: '[]',
    tagIds: JSON.stringify([TAG_IDS.divine]),
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },

  // === HELPERS / GUIDES ===
  {
    id: NPC_IDS.athena,
    name: 'Athena',
    race: 'God',
    role: 'Goddess of Wisdom',
    background:
      "Grey-eyed Athena, goddess of wisdom and war. She favors Odysseus above all mortals for his cunning mind. Throughout his journey, she advocates for him on Olympus and aids him in disguise. His greatest divine ally.",
    status: 'complete',
    image: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    locationIds: JSON.stringify([LOCATION_IDS.mountOlympus]),
    noteIds: '[]',
    tagIds: JSON.stringify([TAG_IDS.divine, TAG_IDS.ally]),
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: NPC_IDS.tiresias,
    name: 'Tiresias',
    race: 'Shade',
    role: 'Blind Prophet',
    background:
      'The legendary seer of Thebes, now a shade in the Underworld. Even in death, he retains his prophetic gift. Odysseus must consult him to learn the way home—and hear warnings about the trials yet to come.',
    status: 'complete',
    image: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    locationIds: JSON.stringify([LOCATION_IDS.underworld]),
    noteIds: '[]',
    tagIds: JSON.stringify([TAG_IDS.oracle, TAG_IDS.divine]),
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
  {
    id: NPC_IDS.aeolus,
    name: 'Aeolus',
    race: 'Demigod',
    role: 'Keeper of the Winds',
    background:
      'Master of the winds, appointed by Zeus to calm or unleash storms. He lives on the floating island of Aeolia with his twelve children. He gifts Odysseus a bag containing all contrary winds—a gift the crew foolishly opens.',
    status: 'complete',
    image: '',
    scope: 'continuity',
    continuityId: SEED_CONTINUITY_ID,
    originId: '',
    originContinuityId: '',
    forkedAt: '',
    campaignIds,
    locationIds: JSON.stringify([LOCATION_IDS.aeolia]),
    noteIds: '[]',
    tagIds: JSON.stringify([TAG_IDS.divine, TAG_IDS.ally]),
    created: SEED_TIMESTAMP,
    updated: SEED_TIMESTAMP,
  },
];
